"use client";
import { IconRenderer } from '@/components/ui/IconRenderer';
import React, { useState } from 'react';
import {
  Sparkles, Sun, TrendingUp, AlertTriangle, Check, ChevronRight,
  Send, Brain, BarChart3, Bot, MessageSquare
} from 'lucide-react';
import { BriefingItem } from './types';
import { toast } from '@/components/ui/toast';

interface Props {
  briefingItems: BriefingItem[];
}

const ITEM_STYLES: Record<string, { color: string; bg: string }> = {
  positive: { color: 'text-green-400', bg: 'bg-green-500/10' },
  warning: { color: 'text-amber-400', bg: 'bg-amber-500/10' },
  action: { color: 'text-[#2266ec]', bg: 'bg-[#2266ec]/10' },
  neutral: { color: 'text-[#a6a6a6]', bg: 'bg-[#1a1a1a]' },
};

interface StrategicInsight {
  id: string;
  insight: string;
  category: string;
  severity: 'info' | 'warning' | 'opportunity';
  confidence: number;
}

const STRATEGIC_INSIGHTS: StrategicInsight[] = [
  { id: 'si_1', insight: 'Revenue is growing 8% MoM, but support costs are increasing 14% faster. If this trend continues, support will consume 23% of gross margin by Q4.', category: 'Financial', severity: 'warning', confidence: 92 },
  { id: 'si_2', insight: 'Your Education platform (SchoolTrack) has 2.3× higher retention than the Repair platform (RepairDesk). Consider applying SchoolTrack\'s onboarding pattern to RepairDesk.', category: 'Product', severity: 'opportunity', confidence: 88 },
  { id: 'si_3', insight: 'AI token costs rose 23% this week because Analytics AI generated 4× more reports than usual. The spike correlates with Q2 close activities — this is seasonal and expected.', category: 'AI Operations', severity: 'info', confidence: 95 },
  { id: 'si_4', insight: 'CRM Engine has the highest API latency (142ms avg) across all applications. 68% of latency is from unoptimized BigQuery joins on the contacts table.', category: 'Infrastructure', severity: 'warning', confidence: 91 },
  { id: 'si_5', insight: 'Three enterprise organizations are approaching their plan limits simultaneously. Proactive upgrade outreach could generate ~$12,400 in incremental MRR.', category: 'Growth', severity: 'opportunity', confidence: 86 },
];

const SEVERITY_STYLES: Record<string, { color: string; bg: string; border: string }> = {
  info: { color: 'text-[#2266ec]', bg: 'bg-[#2266ec]/10', border: 'border-[#2266ec]/20' },
  warning: { color: 'text-amber-400', bg: 'bg-amber-500/10', border: 'border-amber-500/20' },
  opportunity: { color: 'text-green-400', bg: 'bg-green-500/10', border: 'border-green-500/20' },
};

export function ExecutiveBriefingAI({ briefingItems }: Props) {
  const [commandInput, setCommandInput] = useState('');
  const [commandHistory, setCommandHistory] = useState<{ input: string; response: string }[]>([]);

  const executeCommand = () => {
    if (!commandInput.trim()) return;
    const responses: Record<string, string> = {
      default: `✅ Command acknowledged: "${commandInput}". The Enterprise AI has translated this into a safe, auditable operation and queued it for execution with approval workflow.`,
    };
    setCommandHistory(prev => [...prev, { input: commandInput, response: responses.default }]);
    setCommandInput('');
    toast('Enterprise command queued', { type: 'success' });
  };

  return (
    <div className="space-y-6 font-sans">
      {/* Executive Briefing */}
      <div className="bg-gradient-to-br from-[#2266ec]/10 to-purple-500/5 border border-[#2266ec]/20 rounded-xl p-6 shadow-xl space-y-4">
        <div className="flex items-center gap-3 border-b border-[#2266ec]/20 pb-4">
          <div className="w-10 h-10 rounded-xl bg-[#2266ec] flex items-center justify-center">
            <Sun className="w-5 h-5 text-white" />
          </div>
          <div>
            <h3 className="font-bold text-white text-sm">Good morning, Admin.</h3>
            <p className="text-[10px] text-[#a6a6a6] mt-0.5">
              Here is your daily executive briefing generated by Strategic AI · {new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}
            </p>
          </div>
        </div>

        <div className="space-y-2">
          {briefingItems.map((item, i) => {
            const style = ITEM_STYLES[item.type];
            return (
              <div key={i} className={`flex items-start gap-3 p-3 rounded-xl ${style.bg} border border-transparent`}>
                <IconRenderer name={item.icon} className="w-4 h-4 shrink-0 mt-1" />
                <span className={`text-xs leading-relaxed ${style.color}`}>{item.message}</span>
              </div>
            );
          })}
        </div>

        <div className="bg-[#121212] border border-[#2266ec]/20 rounded-xl p-4 space-y-2">
          <div className="text-xs font-bold text-[#2266ec] flex items-center gap-1.5">
            <ChevronRight className="w-3.5 h-3.5" /> Recommended Actions
          </div>
          <div className="space-y-1.5 text-xs text-[#a6a6a6]">
            <div className="flex items-center gap-2"><span className="text-[#2266ec]">•</span> Increase API cache TTL on CRM Engine to reduce BigQuery load.</div>
            <div className="flex items-center gap-2"><span className="text-[#2266ec]">•</span> Review Finance AI permissions — exceeded token budget twice this week.</div>
            <div className="flex items-center gap-2"><span className="text-[#2266ec]">•</span> Approve pending deployment v2.4.0 (blockchain module).</div>
            <div className="flex items-center gap-2"><span className="text-[#2266ec]">•</span> Initiate upgrade outreach for 3 enterprise organizations approaching plan limits.</div>
          </div>
        </div>
      </div>

      {/* Strategic AI */}
      <div className="bg-[#1a1a1a] border border-[#262626] rounded-xl p-5 shadow-xl space-y-4">
        <div className="flex items-center justify-between border-b border-[#262626] pb-3">
          <h3 className="font-bold text-white text-sm flex items-center gap-2">
            <Brain className="w-4 h-4 text-purple-400" /> Strategic AI — Cross-System Business Intelligence
          </h3>
          <span className="text-[10px] text-[#656565]">Reasoning across all applications</span>
        </div>

        <div className="space-y-3">
          {STRATEGIC_INSIGHTS.map(si => {
            const style = SEVERITY_STYLES[si.severity];
            return (
              <div key={si.id} className={`bg-[#121212] border rounded-xl p-4 space-y-2 ${style.border}`}>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className={`text-[9px] px-1.5 py-0.5 rounded font-bold capitalize ${style.bg} ${style.color}`}>{si.severity}</span>
                    <span className="text-[9px] bg-[#1a1a1a] text-[#a6a6a6] px-1.5 py-0.5 rounded border border-[#262626] font-mono">{si.category}</span>
                  </div>
                  <span className="text-[9px] text-[#656565] font-mono flex items-center gap-1">
                    <Sparkles className="w-3 h-3 text-purple-400" /> {si.confidence}% confidence
                  </span>
                </div>
                <div className="text-xs text-[#a6a6a6] leading-relaxed">{si.insight}</div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Enterprise Command Console */}
      <div className="bg-[#1a1a1a] border border-[#262626] rounded-xl p-5 shadow-xl space-y-4">
        <div className="border-b border-[#262626] pb-3">
          <h3 className="font-bold text-white text-sm flex items-center gap-2">
            <MessageSquare className="w-4 h-4 text-cyan-400" /> Enterprise Command Console
          </h3>
          <p className="text-[10px] text-[#656565] mt-1">Natural language commands translated into safe, auditable operations.</p>
        </div>

        {/* Command History */}
        {commandHistory.length > 0 && (
          <div className="space-y-3 max-h-[250px] overflow-y-auto">
            {commandHistory.map((cmd, i) => (
              <div key={i} className="space-y-2">
                <div className="flex items-start gap-2">
                  <span className="text-xs text-[#2266ec] font-mono mt-0.5">❯</span>
                  <span className="text-xs text-white">{cmd.input}</span>
                </div>
                <div className="bg-[#121212] border border-[#262626] rounded-lg p-3 text-[11px] text-[#a6a6a6] ml-4">
                  {cmd.response}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Command Input */}
        <div className="flex items-center gap-2">
          <div className="flex-1 flex items-center gap-2 bg-[#121212] border border-[#333] rounded-xl px-4 py-2.5">
            <span className="text-[#2266ec] font-mono text-xs">❯</span>
            <input
              type="text"
              value={commandInput}
              onChange={e => setCommandInput(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter') executeCommand(); }}
              placeholder="Pause all AI agents except Finance..."
              className="w-full bg-transparent text-xs text-white outline-none placeholder:text-[#656565]"
            />
          </div>
          <button
            onClick={executeCommand}
            disabled={!commandInput.trim()}
            className={`p-2.5 rounded-xl transition-all ${commandInput.trim() ? 'bg-[#2266ec] text-white' : 'bg-[#1a1a1a] border border-[#262626] text-[#656565]'}`}
          >
            <Send className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
}
