export const THEMES = {
  cyberpunk: {
    sidebar: 'bg-black/90 border-r border-[#00B2FF]/30 text-white backdrop-blur-md',
    sidebarNavItems: 'text-gray-400 hover:text-white hover:bg-[#00B2FF]/10 rounded-none transition-all uppercase tracking-widest text-xs font-mono',
    sidebarNavActive: 'bg-[#00B2FF]/15 text-[#00B2FF] border-r-2 border-[#00B2FF] shadow-[0_0_15px_rgba(0,178,255,0.2)]',
    canvas: 'bg-black text-white relative',
    canvasBg: 'absolute inset-0 z-0 opacity-20 pointer-events-none bg-[linear-gradient(rgba(0,178,255,0.05)_1px,transparent_1px),linear-gradient(90deg,rgba(0,178,255,0.05)_1px,transparent_1px)] bg-[length:40px_40px]',
    title: 'text-2xl font-bold uppercase tracking-wider text-white',
    subtitle: 'text-xs text-[#00B2FF] font-mono tracking-widest',
    card: 'bg-gray-900/40 border border-gray-800 rounded z-10 relative',
    tableHeader: 'bg-black border-b border-gray-800 text-[#00B2FF] font-mono text-[10px] uppercase tracking-widest',
    tableRow: 'border-b border-gray-800 hover:bg-gray-900/60 hover:border-[#00B2FF]/50 transition-colors',
    tableCell: 'text-sm text-gray-300',
    primaryButton: 'bg-[#00B2FF]/10 border border-[#00B2FF] text-[#00B2FF] hover:bg-[#00B2FF] hover:text-black hover:shadow-[0_0_20px_rgba(0,178,255,0.4)] transition-all font-bold tracking-widest uppercase text-xs px-4 py-2 rounded-none',
    secondaryButton: 'text-gray-400 hover:text-white transition-colors',
    input: 'bg-gray-900 border border-gray-700 focus:border-[#00B2FF] text-white rounded-none p-3 w-full outline-none font-mono text-sm',
    label: 'text-xs text-gray-500 uppercase tracking-widest font-mono mb-1 block',
    modal: 'bg-gray-900 border border-[#00B2FF]/30 shadow-[0_0_40px_rgba(0,178,255,0.15)] rounded-none',
  },
  ecommerce: {
    sidebar: 'bg-slate-900 text-white',
    sidebarNavItems: 'text-slate-400 hover:text-white hover:bg-white/5 rounded-xl transition-colors font-medium text-sm mx-2',
    sidebarNavActive: 'bg-[#fbbf24] text-white shadow-lg shadow-[#fbbf24]/20',
    canvas: 'bg-slate-50 text-slate-900',
    canvasBg: 'hidden',
    title: 'text-3xl font-black tracking-tight text-slate-900',
    subtitle: 'text-[10px] font-bold text-slate-400 uppercase tracking-widest',
    card: 'bg-white rounded-[24px] border border-slate-100 shadow-[0_8px_30px_rgb(0,0,0,0.04)] overflow-hidden z-10 relative',
    tableHeader: 'bg-slate-50/50 border-b border-slate-100 text-[10px] font-bold text-slate-400 uppercase tracking-widest',
    tableRow: 'border-b border-slate-50 hover:bg-slate-50/50 transition-colors group',
    tableCell: 'text-sm font-medium text-slate-600',
    primaryButton: 'bg-slate-900 text-white hover:bg-slate-800 hover:shadow-lg hover:-translate-y-0.5 hover:shadow-slate-900/20 rounded-xl px-5 py-2.5 text-sm font-semibold transition-all',
    secondaryButton: 'text-slate-400 hover:text-brand-600 hover:bg-brand-50 p-2 rounded-lg transition-colors',
    input: 'bg-slate-50 border-transparent focus:bg-white focus:border-[#fbbf24] focus:ring-2 focus:ring-[#fbbf24]/20 rounded-xl px-5 py-3 w-full font-semibold text-slate-700 outline-none transition-all',
    label: 'block text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1.5',
    modal: 'bg-white rounded-3xl shadow-2xl overflow-hidden',
  },
  default: {
    sidebar: 'bg-[#0a0a0a] border-r border-[#262626]',
    sidebarNavItems: 'text-[#a6a6a6] hover:text-white hover:bg-[#1a1a1a] rounded-lg transition-colors text-[13px] font-medium mx-2',
    sidebarNavActive: 'bg-[#2266ec] text-white',
    canvas: 'bg-[#0a0a0a] text-white',
    canvasBg: 'hidden',
    title: 'text-xl font-bold text-white',
    subtitle: 'text-xs text-[#656565] font-mono',
    card: 'border border-[#262626] rounded-lg overflow-hidden',
    tableHeader: 'bg-[#1a1a1a] border-b border-[#262626] text-[10px] font-bold text-[#656565] uppercase tracking-wider',
    tableRow: 'border-b border-[#262626] hover:bg-[#1a1a1a]/50 transition-colors',
    tableCell: 'text-[13px] text-[#e0e0e0]',
    primaryButton: 'bg-[#2266ec] hover:bg-[#1d57cc] text-white rounded-lg px-4 py-2 text-xs font-bold transition-colors',
    secondaryButton: 'text-[#a6a6a6] hover:text-white p-1.5 rounded hover:bg-[#262626] transition-colors',
    input: 'bg-[#1a1a1a] border border-[#262626] focus:border-[#2266ec] text-white rounded-lg px-3 py-2 w-full outline-none text-sm transition-colors',
    label: 'block text-[11px] text-[#a6a6a6] font-bold uppercase tracking-wider mb-1.5',
    modal: 'bg-[#121212] border border-[#333] rounded-2xl shadow-2xl',
  }
};
